language: C

script:
  # Install the Tor proxy
  - sudo apt-get install tor
  - sudo service tor start

  # Compile and run
  - gcc -mtune=native -O3 -Wall -o jojo -pthread -std=c11 libdill/libdill.a main.c
  - ./jojo
