language: C

script:
  # Install the Tor proxy
  - sudo apt-get install tor
  - sudo service tor start

  # Install OpenSSL
  - sudo cp /usr/include/openssl openssl-headers/*
  - sudo cp openssl-lib/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.1

  # Install LibDill
  - wget http://libdill.org/libdill-2.14.tar.gz
  - tar -xzf libdill-2.14.tar.gz > none
  - cd libdill-2.14
  - ./configure --enable-tls > none
  - make --jobs=4 > none
  - sudo make install > none

  # Compile and run
  - gcc -mtune=native -O3 -Wall -o jojo -ldill main.c
  - ./jojo
